import type { Metadata } from "next";
import localFont from "next/font/local";
import dynamic from "next/dynamic";
import "./globals.css";

const proximaNova = localFont({
  src: [
    {
      path: "./fonts/ProximaNova-Regular.woff",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./fonts/ProximaNova-Regular.woff2",
      weight: "normal",
      style: "normal",
    },
    {
      path: "./fonts/ProximaNova-Bold.woff",
      weight: "bold",
      style: "bold",
    },
    {
      path: "./fonts/ProximaNova-Bold.woff2",
      weight: "bold",
      style: "bold",
    },
    {
      path: "./fonts/ProximaNovaA-Extrabld.woff",
      weight: "900",
      style: "extra-bold",
    },
    {
      path: "./fonts/ProximaNovaA-Extrabld.woff2",
      weight: "900",
      style: "extra-bold",
    },
  ],
  display: "fallback",
});
const MainLayout = dynamic(() => import("@/layouts/main-layout"));

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${proximaNova.className} min-h-screen`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
